#
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            - { position: top, type: sonata.block.service.text, settings: { content: "<h2>rzproject cms-sandbox</h2> <p>CMS built on top of Synfony2 and SonataBundles.</p>"} }
            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
            - { position: center, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: admin }}
            - { position: center, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: admin }}
            - { position: center, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 10 }}
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss, mode: admin }}

        groups:
            CMS:
                items:
                   - sonata.page.admin.site
                   - sonata.page.admin.page
                   - sonata.media.admin.media
                   - sonata.media.admin.gallery
                   - sonata.news.admin.post
                   - sonata.news.admin.comment
            System:
                items:
                   - sonata.classification.admin.context
                   - sonata.classification.admin.collection
                   - sonata.classification.admin.category
                   - sonata.classification.admin.tag
                   - sonata.notification.admin.message
            User:
                items:
                   - sonata.user.admin.user
                   - sonata.user.admin.group
#    assets:
#        stylesheets:
#            # The sandbox includes default pre-optimized version of some css and js
#            # So you can either use them, and add your custom assets here
#            #   ~ or ~
#            # tweak the assetic.yml and the following lines
#            - assetic/sonata_admin_css.css
#
#        javascripts:
#            - assetic/sonata_admin_js.js