# Enable Doctrine to map the provided entities
#doctrine:
#    orm:
#        entity_managers:
#            default:
#                mappings:
#                    FOSUserBundle: ~
#                    ApplicationSonataUserBundle: ~
#                    SonataUserBundle: ~


sonata_user:
    security_acl:     false
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group

    impersonating:
        route:                page_slug
        parameters:           { path: / }

    google_authenticator:
        server:               %sonata_user.google_authenticator.server%
        enabled:              true

    manager_type:             orm

    profile:
        register:
            confirm:
              redirect:
                  # Set it to false to disable redirection
                  route: 'fos_user_profile_show'
                  route_parameters: ~
        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
                - { position: left, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
                - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
                - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
        # Customize user portal menu by setting links
        menu:
            - { route: 'fos_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'fos_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'fos_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
            - { route: 'fos_user_security_logout', label: 'Logout', domain: 'SonataUserBundle'}